"""add arrival created_at and iot dashboard support

Revision ID: 01164ac686c0
Revises: 2e7dd185fd64
Create Date: 2026-03-12 19:20:49.894959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01164ac686c0'
down_revision = '2e7dd185fd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrivals', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
