"""bus centric rfid arrival schema

Revision ID: 7e34e9a3dfbe
Revises: f25bfb7366a3
Create Date: 2026-03-15 12:46:38.995111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e34e9a3dfbe'
down_revision = 'f25bfb7366a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_arrival_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('rfid_uid', sa.String(length=100), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_arrival_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_arrival_logs_arrival_time'), ['arrival_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_arrival_logs_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_arrival_logs_bus_number'), ['bus_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_arrival_logs_rfid_uid'), ['rfid_uid'], unique=False)

    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_plate', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('driver_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('driver_license', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('route', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['license_plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('route')
        batch_op.drop_column('driver_license')
        batch_op.drop_column('driver_name')
        batch_op.drop_column('license_plate')

    with op.batch_alter_table('bus_arrival_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_arrival_logs_rfid_uid'))
        batch_op.drop_index(batch_op.f('ix_bus_arrival_logs_bus_number'))
        batch_op.drop_index(batch_op.f('ix_bus_arrival_logs_bus_id'))
        batch_op.drop_index(batch_op.f('ix_bus_arrival_logs_arrival_time'))

    op.drop_table('bus_arrival_logs')
    # ### end Alembic commands ###
