"""add gps optional bus location support

Revision ID: f25bfb7366a3
Revises: 01164ac686c0
Create Date: 2026-03-15 11:59:16.900244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25bfb7366a3'
down_revision = '01164ac686c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_locations_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_locations_timestamp'), ['timestamp'], unique=False)

    op.create_table('bus_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('last_scan_time', sa.DateTime(), nullable=False),
    sa.Column('last_student_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bus_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_status_bus_id'), ['bus_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bus_status_last_student_id'), ['last_student_id'], unique=False)

    op.create_table('rfid_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfid_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfid_logs_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfid_logs_scan_time'), ['scan_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfid_logs_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfid_logs_uid'), ['uid'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid_uid', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_rfid_uid'), ['rfid_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_rfid_uid'))
        batch_op.drop_column('rfid_uid')

    with op.batch_alter_table('rfid_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfid_logs_uid'))
        batch_op.drop_index(batch_op.f('ix_rfid_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_rfid_logs_scan_time'))
        batch_op.drop_index(batch_op.f('ix_rfid_logs_bus_id'))

    op.drop_table('rfid_logs')
    with op.batch_alter_table('bus_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_status_last_student_id'))
        batch_op.drop_index(batch_op.f('ix_bus_status_bus_id'))

    op.drop_table('bus_status')
    with op.batch_alter_table('bus_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_locations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bus_locations_bus_id'))

    op.drop_table('bus_locations')
    # ### end Alembic commands ###
